import { Copy, Terminal } from 'lucide-react'
import { useState } from 'react'
import { usePackageSelection } from '../../../app/providers/PackagesProvider'

function EmptyTerminalMessage() {
    return (
        <div className="flex flex-1 flex-col items-center justify-center gap-2 p-6 text-center text-xs text-app-text-muted">
            <Terminal aria-hidden="true" size={40} className="opacity-50" />
            <p>Select packages to generate your install script.</p>
        </div>
    )
}

export default function InstallScript() {
    const { selectedPackages } = usePackageSelection()
    const [copied, setCopied] = useState(false)

    const script = [
        '#!/usr/bin/env bash',
        'set -euo pipefail',
        '',
        '# Generated by DevPack',
        ...selectedPackages.map((pack) =>
            pack.installCommand
                ? pack.installCommand
                : `# Installation command for ${pack.name} is not configured yet`,
        ),
    ].join('\n')

    async function handleCopy() {
        if (!selectedPackages.length) return

        try {
            await navigator.clipboard.writeText(script)
            setCopied(true)
            window.setTimeout(() => setCopied(false), 1600)
        } catch {
            setCopied(false)
        }
    }

    return (
        <section className="flex h-full min-h-72 flex-col overflow-hidden rounded-xl border border-app-border-strong bg-terminal-bg" aria-labelledby="install-script-title">
            <div className="flex items-center justify-between border-b border-app-border bg-app-bg-surface px-4 py-2 text-sm">
                <h2 id="install-script-title" className="flex items-center gap-2 text-xs font-semibold tracking-wide">
                    <Terminal aria-hidden="true" size={15} />
                    INSTALL SCRIPT
                </h2>
                <button
                    type="button"
                    disabled={!selectedPackages.length}
                    onClick={handleCopy}
                    className="flex items-center gap-1.5 rounded px-2 py-1 text-xs text-app-text-muted transition-colors hover:text-app-white disabled:cursor-not-allowed disabled:opacity-40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"
                >
                    <Copy aria-hidden="true" size={13} />
                    {copied ? 'Copied' : 'Copy'}
                </button>
            </div>

            <div className="flex min-h-0 flex-1 overflow-auto">
                {selectedPackages.length === 0 ? (
                    <EmptyTerminalMessage />
                ) : (
                    <pre className="w-full whitespace-pre-wrap p-4 font-mono text-xs leading-5 text-app-text-muted">
                        <code>{script}</code>
                    </pre>
                )}
            </div>

            <div className="border-t border-app-border bg-app-bg px-2 py-2">
                <ul className="grid grid-cols-3 gap-2 text-center text-[11px]">
                    <li className="text-app-text-muted">
                        <span className="block text-primary font-semibold">{selectedPackages.length}</span>
                        packages
                    </li>
                    <li className="text-app-text-muted">
                        <span className="block text-primary font-semibold">
                            {new Set(selectedPackages.map((pack) => pack.category)).size}
                        </span>
                        categories
                    </li>
                    <li className="text-app-text-muted">
                        <span className="block text-primary font-semibold">
                            {selectedPackages.filter((pack) => pack.installCommand).length}
                        </span>
                        commands
                    </li>
                </ul>
            </div>
        </section>
    )
}
