import type { Package } from '../types/package.types'

export type GeneratedScript = {
    content: string
    aptPackageCount: number
    snapCommandCount: number
    manualPackageCount: number
}

export function generateInstallScript(selectedPackages: Package[]): GeneratedScript {
    const aptPackages = new Set<string>()
    const snapCommands: string[] = []
    const manualPackages: Package[] = []
    const notes: string[] = []

    for (const pkg of selectedPackages) {
        if (pkg.install.manager === 'apt') {
            for (const packageName of pkg.install.packages ?? []) {
                aptPackages.add(packageName)
            }
            if (pkg.install.note) notes.push(`${pkg.name}: ${pkg.install.note}`)
            continue
        }

        if (pkg.install.manager === 'snap' && pkg.install.command) {
            snapCommands.push(pkg.install.command)
            if (pkg.install.note) notes.push(`${pkg.name}: ${pkg.install.note}`)
            continue
        }

        manualPackages.push(pkg)
        if (pkg.install.note) notes.push(`${pkg.name}: ${pkg.install.note}`)
    }

    const lines = [
        '#!/usr/bin/env bash',
        'set -euo pipefail',
        '',
        '# Generated by DevPack',
        '# Review this script before executing it.',
    ]

    if (aptPackages.size) {
        lines.push('', 'sudo apt update', `sudo apt install -y ${[...aptPackages].join(' ')}`)
    }

    if (snapCommands.length) {
        lines.push('', '# Snap packages')
        lines.push(...snapCommands)
    }

    if (manualPackages.length) {
        lines.push('', '# Packages requiring manual installation')
        for (const pkg of manualPackages) {
            lines.push(`# ${pkg.name}: ${pkg.install.note ?? 'No automatic recipe configured.'}`)
        }
    }

    if (notes.length) {
        const uniqueNotes = [...new Set(notes)]
        lines.push('', '# Package notes')
        for (const note of uniqueNotes) lines.push(`# ${note}`)
    }

    if (!selectedPackages.length) {
        lines.push('', '# No packages selected.')
    }

    return {
        content: `${lines.join('\n')}\n`,
        aptPackageCount: aptPackages.size,
        snapCommandCount: snapCommands.length,
        manualPackageCount: manualPackages.length,
    }
}
